/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Tiers = t.iface([], {
  "solo": t.union("UnrankedTier", "RankedTier"),
  "team": t.union("UnrankedTier", "RankedTier"),
});

export const UnrankedTier = t.iface([], {
  "tier": "string",
  "tierImage": "string",
});

export const RankedTier = t.iface(["UnrankedTier"], {
  "rank": "string",
  "leaguePoints": "number",
  "wins": "number",
  "losses": "number",
});

const exportedTypeSuite: t.ITypeSuite = {
  Tiers,
  UnrankedTier,
  RankedTier,
};
export default exportedTypeSuite;
